---
## roles/resources/tasks/debian.yml
#
#

# ensure for requirements

## apt packages

#- name: "update apt cache"
#  become: true
#  apt:
#    update_cache: yes
#    cache_valid_time: 3600
#  tags: [ 'packages' ]

- name: "Install git clone reqirements"
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name : '{{ item }}'
    state: 'present'
  with_items:
    - git
