---
## roles/resources/tasks/debian.yml
#
#

# ensure for requirements

- name: "Install git clone reqirements"
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
    name: '{{ item }}'
    state: 'present'
  with_items:
    - git
